name: revision_flutter
description: "A playground for learning flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: LXGW Kai
      fonts:
        - asset: fonts/lxgw-wenkai/LXGWWenKaiTC-Bold.ttf
          weight: 700
        - asset: fonts/lxgw-wenkai/LXGWWenKaiTC-Regular.ttf
        - asset: fonts/lxgw-wenkai/LXGWWenKaiTC-Light.ttf
          weight: 300
    - family: GenSeki
      fonts:
        - asset: fonts/GenSekiGothic/GenSekiGothic-R.ttc
        - asset: fonts/GenSekiGothic/GenSekiGothic-B.ttc
          weight: 700
        - asset: fonts/GenSekiGothic/GenSekiGothic-L.ttc
          weight: 300
